# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8e26de3aa5e893edd63ca0aa3be7756b7c808a656a802b5fdce4206ab4bd1f2e427242ab4e6f36c075ab565d16b8e4c01f0ac09faee5474f03a407704b1f9d3

test:
  secret_key_base: 07df238e65b362bfa279e21fc495337a176bd2e495a8bdadf27b50c69974161cf655fae1c22576f831d1834ea3f96cb226de90380f9e798b866e652c28247a89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
